// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    ContextMenu: typeof import('./src/components/CreateFlow/components/ContextMenu/src/ContextMenu.vue')['default']
    CreateFlow: typeof import('./src/components/CreateFlow/index.vue')['default']
    ECharts: typeof import('./src/components/ECharts/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FlowArea: typeof import('./src/components/CreateFlow/components/FlowArea.vue')['default']
    FlowAttr: typeof import('./src/components/CreateFlow/components/FlowAttr.vue')['default']
    FlowElement: typeof import('./src/components/CreateFlow/components/FlowElement.vue')['default']
    FlowElementList: typeof import('./src/components/CreateFlow/components/FlowElementList.vue')['default']
    FlowNode: typeof import('./src/components/CreateFlow/components/FlowNode.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/index.vue')['default']
    SettingModal: typeof import('./src/components/CreateFlow/components/SettingModal.vue')['default']
    ShortcutKeyModal: typeof import('./src/components/CreateFlow/components/ShortcutKeyModal.vue')['default']
    TestModal: typeof import('./src/components/CreateFlow/components/TestModal.vue')['default']
    Toolbar: typeof import('./src/components/CreateFlow/components/Toolbar.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo/index.vue')['default']
  }
}
